site_name: OpenPecha
theme:
  name: material
nav:
  - Introduction: index.md
  - OPF Format: opf-format.md
  - Importers: importers.md
  - Exporters: exporters.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed
